/* QUESTION_GROUP */
export const RECEIVE_QUESTION_GROUPS = 'RECEIVE_QUESTION_GROUPS';
export const RECEIVE_QUESTION_GROUP = 'RECEIVE_QUESTION_GROUP';
export const ADD_QUESTION_GROUP = 'ADD_QUESTION_GROUP';
export const UPDATE_QUESTION_GROUP = 'UPDATE_QUESTION_GROUP';
export const REMOVE_QUESTION_GROUP = 'REMOVE_QUESTION_GROUP';
export const QUESTION_GROUPS_ERROR = 'QUESTION_GROUPS_ERROR';
