/* QUESTION */
export const RECEIVE_SURVEY_QUESTIONS = 'RECEIVE_SURVEY_QUESTIONS';
export const RECEIVE_QUESTIONS_BY_GROUP_ID = 'RECEIVE_QUESTIONS_BY_GROUP_ID';

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION';

